### PR TITLE
For upstream

### PR DESCRIPTION
**Pull request by jkent**
* Add bssid to results
* Turn RPC result into an array like RPC.List

### CODE REVIEW

**Comment by rojer** [comment]
makes sense, will integrate

**Comment by rojer** [comment]
i sent a change to integrate this into our internal repo. once it lands, this PR will be automatically closed and once the change is published you will see a commit attached to it.
thanks!

**Comment by jkent** [comment]
One small note; you looked over the changes to the Readme.md !

**Comment by rojer** [comment]
indeed. i sent a followup.

**Pull request closed without merging**
